version: '3.7'
services:
    pgdev:
        image: postgres:alpine
        mem_limit: 512m
        mem_reservation: 128M
        environment:
            - POSTGRES_USER=root
            - POSTGRES_PASSWORD=root
            - POSTGRES_DB=pgdev
        ports: 
            - 5432:5432
        logging:
            options:
                max-size: 10m
                max-file: "3"
    pghml:
        image: postgres:alpine
        mem_limit: 512m
        mem_reservation: 128M
        environment:
            - POSTGRES_USER=root
            - POSTGRES_PASSWORD=root
            - POSTGRES_DB=pghml
        ports: 
            - 5433:5432
        logging:
            options:
                max-size: 10m
                max-file: "3" 
    pgprd:
        image: postgres:alpine
        mem_limit: 512m
        mem_reservation: 128M
        environment:
            - POSTGRES_USER=root
            - POSTGRES_PASSWORD=root
            - POSTGRES_DB=pgprd
        ports: 
            - 5434:5432
        logging:
            options:
                max-size: 10m
                max-file: "3"